# Jack Rabbit Tests Makefile
# jsp Fri Feb  6 17:17:03 CST 2009

CCFILES=$(shell ls -1 *.cc)
TARGETS=$(basename $(CCFILES))
INCLUDEPATH=/home/jsp/Projects
DEPENDPATH=/home/jsp/Projects
EXTRA_SOURCES=
LIBS=-lfftw3

include /home/jsp/Projects/Makefile.tests
